rh-ecosystem-edge/recert

src/cluster_crypto/yaml_crawl.rs
src/rules.rs

This rule is unnecessary as we dont'/won't have clusters of any kind for any purpose, which would include these types of certs.
This reverts commit 548e9102760195199d41e354765326b181ff0283.

Revert "Ignore entitlement machine-config certs that are generated by the PSAP ci-cluster repo we use for testing"

---

README.md

Without this the etcd container failed with:
```
{"level":"fatal","ts":"2023-08-23T18:10:22.892024Z","caller":"etcdmain/etcd.go:435","msg":"failed to list data directory","dir":"/store","error":"open /store: permission denied","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.identifyDataDirOrDie\n\tgo.etcd.io/etcd/server/v3/etcdmain/etcd.go:435\ngo.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\tgo.etcd.io/etcd/server/v3/etcdmain/etcd.go:114\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\tgo.etcd.io/etcd/server/v3/etcdmain/main.go:40\nmain.main\n\tgo.etcd.io/etcd/server/v3/main.go:31\nruntime.main\n\truntime/proc.go:250"}
```

Add :Z to the volume arg to podman to deal with selinux

---

src/cluster_crypto/cert_key_pair.rs
src/cluster_crypto/distributed_private_key.rs
src/cluster_crypto/distributed_public_key.rs
src/file_utils.rs

The annotation has a string value that is a serialized json object with
its keys being JSON pointers of fields in the annotated resource and
values being a list of PEM bundle indices that were edited (or "N/A" if
the field was not PEM-encoded).
For example:
```
metadata:
annotations:
...
recert-edited: '{"/spec/config/storage/files/15/contents/source":["1","2","6","5","3","0","4"],"/spec/config/storage/files/21/contents/source":["0"]}'
...
```
This annotation is purely informational and is not used programmatically
by recert itself. It's used to help troubleshooters notice this is not a
"natural" cryptographic object, but instead one that was manipulated by
recert.
Resolves https://issues.redhat.com/browse/MGMT-15538

MGMT-15538: Add an annotation to edited k8s resources

---

.gitmodules
Dockerfile

This PR adds [ouger](https://github.com/rh-ecosystem-edge/ouger) as a git submodule and an additional Dockerfile stage for its building and copying into the recert release image.

Add ouger as a git submodule

---

src/cluster_crypto/scanning.rs

Not all kubeconfigs end with kubeconfig, some just contain that word.
Not all kubeconfigs are lowercase.

Handle weirdly named kubeconfigs as YAML

---

Dockerfile

The resource in question seems to be PIDs. For some reason this seems to
not happen when CGO_ENABLED is set to 0, which IIUC means the pthread
library is not used by Go. I don't entirely understand this, but it
works.

Fix `Resource temporarily unavailable (os error 11)` errors

---

.gitmodules
Cargo.lock
Cargo.toml
Dockerfile
run_seed.sh
src/k8s_etcd.rs
src/main.rs
src/ouger.rs

Instead of invoking thousands of instances of ouger, just send GET
requests to a single instance of ouger_server. This is much faster.
Reduced number of pre-cached RSA keys from 300 to 100.
`run_seed.sh` will now use the etcddump utility (added as a submodule)
to instantly dump etcd, for faster verification of changes during
development.

Switch to using ouger_server instead of ouger

---

.gitignore
Cargo.lock
Cargo.toml
run_seed.sh
src/cli.rs
src/cluster_crypto.rs
src/cluster_crypto/cert_key_pair.rs
src/cluster_crypto/cert_key_pair/cert_mutations.rs
src/cluster_crypto/cert_key_pair/key_identifiers.rs
src/cluster_crypto/certificate.rs
src/cluster_crypto/crypto_objects.rs
src/cluster_crypto/crypto_utils.rs
src/cluster_crypto/distributed_cert.rs
src/cluster_crypto/distributed_jwt.rs
src/cluster_crypto/distributed_private_key.rs
src/cluster_crypto/distributed_public_key.rs
src/cluster_crypto/jwt.rs
src/cluster_crypto/keys.rs
src/cluster_crypto/locations.rs
src/cluster_crypto/signee.rs
src/file_utils.rs
src/main.rs
src/ouger.rs
src/use_cert.rs

The YAML summary is basically a dump of the ClusterCryptoObjects struct
which contains all the information about the running of recert, now also
including copies of the original on top of the regenerated crypto
objects.
More information might be added in the future such as warnings, SAN, etc
Resolves [MGMT-15539](https://issues.redhat.com//browse/MGMT-15539)

Optionally generate a YAML summary

---

run_seed.sh
src/cli.rs
src/cluster_crypto/cert_key_pair.rs
src/cluster_crypto/distributed_jwt.rs
src/cluster_crypto/distributed_private_key.rs
src/cluster_crypto/distributed_public_key.rs
src/file_utils.rs
src/k8s_etcd.rs
src/main.rs
src/ocp_postprocess/cluster_domain_rename/filesystem_rename.rs
src/ouger.rs

Don't actually commit anything to etcd/disk. Useful for validating that
a cluster can be recertified error-free before turning it into a seed
image.
Closes [MGMT-15982](https://issues.redhat.com//browse/MGMT-15982)

Dry run mode

---

src/cluster_crypto.rs
src/cluster_crypto/cert_key_pair.rs
src/cluster_crypto/crypto_utils.rs
src/cluster_crypto/distributed_jwt.rs
src/cluster_crypto/distributed_private_key.rs
src/cluster_crypto/signee.rs
src/rsa_key_pool.rs

This is important for FIPS compliance, we can't rely on random rust
crypto libraries for this.
Resolves [MGMT-15636](https://issues.redhat.com//browse/MGMT-15636)

Use openssl for signing certs

---

src/cluster_crypto.rs
src/cluster_crypto/distributed_private_key.rs
src/cluster_crypto/distributed_public_key.rs
src/cluster_crypto/scanning.rs
src/file_utils.rs
src/main.rs
src/ocp_postprocess.rs
src/ocp_postprocess/cluster_domain_rename.rs
src/ocp_postprocess/cluster_domain_rename/etcd_rename.rs
src/ocp_postprocess/cluster_domain_rename/filesystem_rename.rs

This CR contains copies of the `cluster` Infrastructure CR and the
`cluster` DNS CR, both of which were previously renamed but these copied
embedded within the `machine-config-controller` ControllerConfig CR were
missed
Based on #48, see ff9d3ad for the actual changes

Also rename machine-config-controller ControllerConfig

---

src/ocp_postprocess/cluster_domain_rename.rs
src/ocp_postprocess/cluster_domain_rename/etcd_rename.rs
src/ocp_postprocess/cluster_domain_rename/filesystem_rename.rs
src/ocp_postprocess/cluster_domain_rename/rename_utils.rs

The kubelet kubeconfig (`/etc/kubernetes/kubeconfig`) contains the
cluster's name as a .clusters[].cluster.name, so it needs to be modified

Rename cluster in kubelet kubeconfig

---

Cargo.lock
Cargo.toml
src/cluster_crypto.rs
src/cluster_crypto/cert_key_pair.rs
src/cluster_crypto/crypto_utils.rs
src/cluster_crypto/crypto_utils/jwt.rs
src/cluster_crypto/distributed_jwt.rs
src/cluster_crypto/distributed_private_key.rs
src/cluster_crypto/signee.rs

Drop overkill jwt_simple dependency, it was very annoying to use in our
context anyway. Replaced with `src/cluster_crypto/crypto_utils/jwt.rs`
which uses openssl to verify and sign JWTs.
I think performance may have took a hit with this change
Solves [MGMT-16095](https://issues.redhat.com//browse/MGMT-16095)

JWT signing FIPS compliance

---

src/cluster_crypto.rs
src/cluster_crypto/crypto_utils/jwt.rs
src/cluster_crypto/keys.rs

Otherwise we'll trip like we did in b3695533a8e0a8498c9ea72d94365f3b4aa8267c
Also pretend all EC keys are failing to verify JWTs for now

Unsupported JWT algorithm should be a warning

---

run_seed.sh
src/ocp_postprocess/cluster_domain_rename.rs
src/ocp_postprocess/cluster_domain_rename/params.rs

infra-id is not just a UUID, it's made up from the cluster name + some
random digits, and since recert takes care of doing a rename, it has to
take care of infra-id as well
During a regular OCP installation those digits are random
So IBI recert rename also does random (since we're pretending it's a
fresh cluster)
But IBU recert rename should use the infra-id from the original cluster,
it can't just add random digits.
This commit adds an option for the user to provide their own infra-id to
facilitate IBU
Solves [MGMT-16122](https://issues.redhat.com//browse/MGMT-16122)

Allow user to optionally provide an infra ID

---

src/ocp_postprocess/cluster_domain_rename/rename_utils.rs

In 4.15 this file might just be empty (e.g. `/etc/machine-config-daemon/noorig/etc/kubernetes/apiserver-url.env.mcdnoorig`)

Better handling of empty `apiserver-url.env`

---

src/ocp_postprocess.rs
src/ocp_postprocess/fnv.rs

This should avoid some rollouts

OCPEDGE-654 Fix dep annotations

---

src/cluster_crypto/pem_utils.rs

Replacing is now done by naive search-and-replace on the original bundle
string rather than by parsing and re-emitting the bundle (which loses
the content between the PEM objects in the process)

PEM bundle editing should preserve content between PEM objects

---

Cargo.lock
Cargo.toml
src/ocp_postprocess.rs

The webhook authenticator secret has a kubeConfig field that is too
complicated to handle in recert. We could simply delete it and it will
be reconciled, but that's a bit too slow for us as it causes a
kube-apiserver rollout. To speed things up, we'll just "reconcile" it
ourselves by copying the kubeConfig contents from the kubeConfig file on
disk that we already processed with recert.
Also enable the preserve_order feature of serde_json to make sure field
order is maintained, because those differences also cause rollouts
________________
Older revisions are deleted from etcd, only the latest revision is synced:

Sync webhook-authenticator static secret files

---

src/ocp_postprocess/cluster_domain_rename/etcd_rename.rs

The original `oauth-metadata` file has a pretty JSON, so it should stay
pretty to avoid rollouts

Pretty `oauth-metadata`

---

Dockerfile.prow

In the current CI [dockerfile_literal](https://github.com/openshift/release/blob/master/ci-operator/config/rh-ecosystem-edge/recert/rh-ecosystem-edge-recert-main.yaml#L29), `registry.redhat.io` is used and it supports only authenticated access, but it worked so far because of the respective [from](https://github.com/openshift/release/blob/master/ci-operator/config/rh-ecosystem-edge/recert/rh-ecosystem-edge-recert-main.yaml#L57) directive. 
This PR replaces the authenticated `registry.redhat.io` with the unauthenticated `registry.access.redhat.com`, in order to have successful builds with the `Dockerfile.prow` container file.
The following is the CI [error](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/47035/rehearse-47035-pull-ci-rh-ecosystem-edge-rece …

Use unauthenticated RH registry for prow Dockerfile

---

src/ocp_postprocess/cluster_domain_rename/rename_utils.rs

When renaming, the array was accidentally replaced by a string, this
caused a KCM rollout

KCM extended arguments should be an array

---

src/ocp_postprocess/cluster_domain_rename/etcd_rename.rs

The newline is causing a rollout that we wish to avoid

Add a newline at the end of the kcm pod configmap

---

run_seed.sh
src/cluster_crypto/crypto_utils.rs
src/config.rs
src/config/cli.rs
src/use_cert.rs
src/use_key.rs

As opposed to file paths. This will allow recert to be launched without
having all the keys laid out carefully in files, which is inconvenient
if they aren't already in files

`RECERT_CONFIG` accept keys inlined raw inside the config

---

run_seed.sh
src/config.rs
src/config/cli.rs
src/ocp_postprocess.rs
src/ocp_postprocess/cluster_domain_rename.rs
src/ocp_postprocess/cluster_domain_rename/filesystem_rename.rs
src/ocp_postprocess/cluster_domain_rename/rename_utils.rs
src/ocp_postprocess/hostname_rename.rs
src/ocp_postprocess/hostname_rename/etcd_rename.rs
src/ocp_postprocess/hostname_rename/filesystem_rename.rs
src/recert.rs

This PR adds the changes required to the `ocp_postprocess` module, in order to skip the unnecessary and time-consuming OCP control-plane component rollouts. The latter get triggered by the node's `hostname` change, which occurs when applying an IBU seed image onto the target SNO.
The changes are:

Implement ocp postprocess hostname rename

---

src/ocp_postprocess/cluster_domain_rename/etcd_rename.rs

After switching to search and replace for the kubeconfig field in the respective `kube-controller-manager` and `kube-scheduler` `ConfigMaps`, we shouldn't serialize the edited `kubeconfig` field to YAML, as it includes an additional `|` character. The latter doesn't lead to an error, but it does lead to additional rollout triggers for these components.
Example `kubeconfig` field with the additional `|`:
```json
"data": {
"kubeconfig": "|\n  apiVersion: v1\n  clusters:\n    - cluster:\n        certificate-authority: /etc/kubernetes/static-pod-resources/configmaps/serviceaccount-ca/ca-bundle.crt\n        server: https://api-int.another-name.another.domain:6443\n      name: lb-int\n  contexts:\n    - context:\n        cluster: lb-int\n        user: kube-scheduler\n      name: …
```

Fix kubeconfig YAML serialization in etcd

---

src/ocp_postprocess/cluster_domain_rename.rs
src/ocp_postprocess/cluster_domain_rename/etcd_rename.rs

Accidentally user cluster_domain where it should have been the infra-ID,
this caused a KCM rollout

Fix KCM rollout

---

src/file_utils.rs

These annotations could be a cause for rollouts, so for now avoid them as avoiding rollout is more important than having those annotations

Disable recert-edited annotations

---

src/cluster_crypto.rs
src/cluster_crypto/cert_key_pair.rs
src/cluster_crypto/distributed_private_key.rs
src/cluster_crypto/scanning.rs
src/cluster_crypto/signee.rs
src/config.rs
src/config/cli.rs
src/logging.rs
src/ocp_postprocess.rs
src/ocp_postprocess/cluster_domain_rename.rs
src/ocp_postprocess/cluster_domain_rename/params.rs
src/recert.rs
src/recert/timing.rs

A recent addition of a lot of rename functionality made the code a bit
unreadable.
This commit tucks all rename-related fields into a struct called
`ClusterCustomizations` so passing them around is more neat.
Did the same for timings related code, and put it in a module, so it's
more out of sight from the main code flow.

Tuck some fields into structs

---

src/ocp_postprocess/cluster_domain_rename/rename_utils.rs
src/ocp_postprocess/ip_rename/etcd_rename.rs

This PR fixes the IP replacement when an IPv6 is provided or getting replaced. IPv6 IPs should be enclosed in `[ ] ` when used in URLs, but OpenShift in some cases uses brackets for IPv6 IPs also when found in non-URL fields. For example, in the env vars of the etcd container of the `etcd-pod` manifest:
```YAML
- name: "NODE_sno_test_redhat_com_IP"
value: "[2710:20:0:18::8]"
```
This change ensures that we respect the format of the fields in OCP containing IPv6 IPs (with or without `[ ]`). It also ensures that we support the following cases properly when replacing the  IP:
- seed IPv4 -> recipient IPv4
- seed IPv4 -> recipient IPv6
- seed IPv6 -> recipient IPv4
- seed IPv6 -> recipient IPv6

MGMT-17058: Fix IPv6 replacement by adding brackets when necessary 

---

src/cluster_crypto/cert_key_pair.rs
src/file_utils.rs

This PR ensures that when recert regenerates certs that are found in etcd and include the `auth.openshift.io/certificate-not{after,before}` annotations, it also updates the latter according to their respective validity period.

MGMT-17057: Update auth annotations when regenerating certs found in etcd

---

src/cluster_crypto/cert_key_pair.rs
src/file_utils.rs

This PR ensures that when recert regenerates certs that are found in etcd and include the `auth.openshift.io/certificate-not{after,before}` annotations, it also updates the latter according to their respective validity period.

[release-4.15] MGMT-17057: Update auth.openshift.io/certificate-not{after,before} annotations when regenerating certs

---

src/cluster_crypto/scanning.rs
src/cluster_crypto/scanning/external_certs.rs
src/recert.rs

MCO will observe the `user-ca-bundle` configmap regardless of whether
the proxy resource points at it or not. So recert should consider all
certs inside this configmap to be external.

"user-ca-bundle" should be consider external regardless of proxy

---

src/ocp_postprocess.rs
src/ocp_postprocess/hostname_rename/etcd_rename.rs
src/ocp_postprocess/ip_rename.rs
src/ocp_postprocess/ip_rename/etcd_rename.rs

In OCP 4.16 the cluster-etcd-operator moved to using [library-go/certrotation](https://github.com/openshift/library-go/tree/master/pkg/operator/certrotation) and that leads to the following etcd TLS secrets having annotations that include the IP and the hostname:
- `openshift-etcd/etcd-peer-<hostname>`
- `openshift-etcd/etcd-serving-<hostname>`
- `openshift-etcd/etcd-serving-metrics-<hostname>`
The respective annotations are:
- `auth.openshift.io/certificate-hostnames` - this includes the IP
- `openshift.io/description` - this includes the hostname
Recert now replaces the IP and the hostname in those annotations, in order to skip an additional etcd rollout that is triggered because of the former.
Resources:
- https://github.com/openshift/cluster-etcd-operator/pull/1194
- …

MGMT-17319: Fix etcd secrets annotations for OCP >4.16

---

src/ocp_postprocess/proxy_rename/etcd_rename.rs
src/ocp_postprocess/proxy_rename/filesystem_rename.rs
src/ocp_postprocess/proxy_rename/utils.rs

None of such files have PROXY env vars so we can skip them. We don't
want to parse them and then re-serialize them as that could cause
formatting changes which could lead to rollouts.

Don't modify proxy on non-JSON YAML files

---

src/logging.rs
src/main.rs

When recert runs into an error, it returns it as a `Result` from the
`main` function. This causes the Rust runtime to print the error trace.
However, the error does not get included in the recert summary files. In
the summary, you only see the logs, which makes it look like no error
occurred.
This commit makes it so that when recert runs into an error the error
will be included in summary files

Include error in recert summary

---

src/ocp_postprocess/proxy_rename/etcd_rename.rs
src/ocp_postprocess/proxy_rename/utils.rs

recert recently added a `--proxy` feature that replaces the proxy configuration in the cluster
The `--proxy` feature is not working as expected, some rollouts happen due to the order of the proxy env vars in the kube-apiserver's and kube-controller-manager's container's env. Seems to happen a few times before the cluster stabilizes
This is simply because of a typo in the code, the `HTTP_PROXY` and `HTTPS_PROXY` env vars are being swapped in the `generic_proxy_fix` function
Solves OCPBUGS-33471
Fix the typo in the `generic_proxy_fix` function
The back-and-forth rollouts in e.g. kube-apiserver are due to the `KubeAPIServer` CR being at first in correct, which causes the deployment of the `kube-apiserver` to change, then another controller reads the fixes the `KubeAPIServer` CR itself, which …

OCPBUGS-33471: Fix proxy ordering

---

hack/dummy_config.yaml
run_seed.sh
src/config.rs
src/config/cli.rs
src/ocp_postprocess.rs
src/ocp_postprocess/chrony_config.rs
src/ocp_postprocess/chrony_config/etcd_rename.rs
src/ocp_postprocess/chrony_config/filesystem_rename.rs
src/ocp_postprocess/chrony_config/utils.rs
src/ocp_postprocess/cluster_domain_rename.rs
src/ocp_postprocess/cluster_domain_rename/etcd_rename.rs
src/ocp_postprocess/hostname_rename/etcd_rename.rs
src/ocp_postprocess/hostname_rename/filesystem_rename.rs
src/ocp_postprocess/ip_rename/etcd_rename.rs
src/ocp_postprocess/pull_secret_rename/etcd_rename.rs
src/ocp_postprocess/pull_secret_rename/filesystem_rename.rs
src/ocp_postprocess/rename_utils.rs

OCPBUGS-32553: post-pivot does not restore ntp servers
As part of cluster creation assisted-service or user creates machine config that changes /etc/chrony.conf file in order to setup ntp servers. We need to allow copying this configuration from target sno to updated cluster.
Current change allows to provide recert with new chrony.conf that will be changed in all machine configs + /etc/chrony.conf. This pr also makes some function generic in order to reuse the logic

OCPBUGS-32553: post-pivot does not restore ntp servers

---

Dockerfile

NO-ISSUE: adding openssh package to recert image in order to generate ssh keys in IBI process

NO-ISSUE: adding openssh package to recert image in order to generate ssh keys in IBI process

---

Dockerfile

IBI is currently broken because it requires https://github.com/rh-ecosystem-edge/recert/pull/150

Sync v0 to latest master

---

Dockerfile

IBI requires https://github.com/rh-ecosystem-edge/recert/pull/150

Sync release-4.16 to latest master

---

src/ocp_postprocess/ip_rename.rs
src/ocp_postprocess/ip_rename/etcd_rename.rs
src/ocp_postprocess/ip_rename/filesystem_rename.rs
src/ocp_postprocess/rename_utils.rs

[MGMT-16961](https://issues.redhat.com//browse/MGMT-16961): Support replacing the IP on the filesystem
Till this PR recert only updated IP in etcd and we relied on LCA to update the filesystem. This code adds logic to update ip in all required files inside /etc/kubernetes. We replace old ip with new one file by file.

MGMT-16961: Support replacing the IP on the filesystem

---

src/k8s_etcd.rs

Solves [MGMT-17651](https://issues.redhat.com//browse/MGMT-17651)
A fix for a rare error:
```
Error: finalizing
Caused by:
0: commiting etcd cache to actual etcd
1: grpc request error: status: Unknown, message: "etcdserver: too many requests", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```
When committing our in-memory etcd representation to actual etcd, we send all delete requests concurrently (we have many).
Sometimes this leads to us receiving an error from etcd which says "etcdserver: too many requests". Recert treated this error as a hard error and as a result it exits.
Compare the error string to this exact phrasing (as there doesn't seem to be a more robust error code we can check, the code just says `Unknown`), and if we encounter it, just …

Retry on etcd too many requests error

---

src/ocp_postprocess.rs

This PR updates the `ClusterVersion`'s status condition of type `Available` to `status: "False"`, along with its `message: "Cluster version status unknown"`, in the OCP post-processing step of recert.
/cc @tsorya

Set CVO available condition to False

---

src/k8s_etcd.rs
src/ocp_postprocess/ip_rename.rs
src/ocp_postprocess/ip_rename/etcd_rename.rs

This commit implements logic from lca https://github.com/openshift-kni/lifecycle-agent/blob/main/lca-cli/postpivot/postpivot.go#L358
As we moved all the ip change logic into recert we should handle this part here too.
This code updates existing member with new ip

Setting new ip to etcd member

---

.tekton/build-pipeline.yaml
.tekton/recert-4-16-pull-request.yaml
.tekton/recert-4-16-push.yaml

For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Based on original changes from @rbean in our other operator repos
Assisted-by: Gemini

[release-4.16] chore(KONFLUX-6210): fix and set name and cpe label for recert

---

.tekton/build-pipeline.yaml
.tekton/recert-4-17-pull-request.yaml
.tekton/recert-4-17-push.yaml

For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Based on original changes from @rbean in our other operator repos
Assisted-by: Gemini

[release-4.17] chore(KONFLUX-6210): fix and set name and cpe label for recert

---

.tekton/recert-4-20-pull-request.yaml
.tekton/recert-4-20-push.yaml

- Should now target the branch `release-4.20` instead of `main`
AI-attribution: AIA,Entirely human-created,v1.0
For more information on AI attribution statements, see: https://aiattribution.github.io/

[release-4.20] Update target branch for 4.20 builds
