- Cargo.lock
- Cargo.toml
- src/cluster_crypto/scanning.rs
- src/cluster_crypto/yaml_crawl.rs
- src/file_utils.rs
- src/k8s_etcd.rs
- src/ocp_postprocess/cluster_domain_rename/etcd_rename.rs
Also changes the dataurl encoding to more closely match what's done by
the encoder used in MCO
These changes should prevent diffs in the machine config and hopefully
avoid reboot trigger by MCO
> Add support for ControllerConfigs

- src/cluster_crypto.rs
- src/cluster_crypto/distributed_jwt.rs
- src/cluster_crypto/scanning.rs
See commit messages for more information
> Better handling for external certs and external JWTs

- run_seed.sh
- src/main.rs
See commit messages for more information
> Various fixes

- .gitignore
- run_seed.sh
- src/cli.rs
- src/cluster_crypto.rs
- src/cluster_crypto/jwt.rs
- src/cluster_crypto/keys.rs
- src/file_utils.rs
- src/main.rs
> Clean summary

- src/ocp_postprocess.rs
These kubeconfigs nested inside a secret are far too complicated to
handle in recert, so we just delete them and hope that a reconcile will
take care of them. We've seen that sometimes a controller will sync them
back to the filesystem, which we cannot afford
> Delete secret `openshift-kube-apiserver/node-kubeconfigs`

- src/cli.rs
- src/cluster_crypto/cert_key_pair.rs
- src/cluster_crypto/cert_key_pair/cert_mutations.rs
See commit message for info
Closes [MGMT-16020](https://issues.redhat.com//browse/MGMT-16020)
> Force expiry

- README.md
- run_seed.sh
Less chance of failing on new machines
> Improve docs / run_seed.sh instructions

- src/cnsanreplace.rs
Also remove old space separation as it's not used anywhere
> Also allow comma separation for CnSanReplace to support IPv6

- src/cluster_crypto/scanning.rs
We do not want to regenerate them as they are external to the cluster.
This commit adds ConfigMap/openshift-config:user-ca-bundle
/data/ca-bundle.crt as a location where we scan to determine which
certificates are external and should be ignored
cc @mcornea
> Consider user-ca-bundle certificates as external

- src/cluster_crypto/distributed_public_key.rs
This happens to public keys without any associated private keys. This
happens when private keys are rotated, lost, and their remnants remain
in some old static configmap revisions
In the future we should just regenerate all public keys regardless of
the presence of their private keys
> Pub key not regenerated should be just warning

- src/cluster_crypto.rs
- src/cluster_crypto/distributed_private_key.rs
- src/cluster_crypto/distributed_public_key.rs
- src/cluster_crypto/scanning.rs
- src/file_utils.rs
- src/main.rs
- src/ocp_postprocess.rs
- src/ocp_postprocess/cluster_domain_rename.rs
- src/ocp_postprocess/cluster_domain_rename/filesystem_rename.rs
Rename should fix `/etc/mcs-machine-config-content.json` as well
This PR is based on https://github.com/rh-ecosystem-edge/recert/pull/47 to
avoid conflicts, see 0c66fb1 for the actual change.
> Rename filesystem mcs machine config content

- config_example.yaml
- src/cli.rs
- src/cli/config.rs
- src/cluster_crypto.rs
- src/cluster_crypto/cert_key_pair.rs
- src/cluster_crypto/distributed_private_key.rs
- src/cluster_crypto/signee.rs
- src/main.rs
This is an alternative to passing all the information through CLI flags
Solves [MGMT-16150](https://issues.redhat.com//browse/MGMT-16150)
> Parse config from RECERT_CONFIG file

- src/cluster_crypto.rs
- src/cluster_crypto/distributed_public_key.rs
Solves [MGMT-16118](https://issues.redhat.com//browse/MGMT-16118)
> Regenerate unassociated standalone public keys

- src/cli.rs
- src/cli/config.rs
Also organize code around CLI parsing
> Improve RECERT_CONFIG error message

- src/logging.rs
- src/main.rs
- src/recert.rs
The summary will now include a breakdown of how long each stage of the
recertification process took
We've seen instances where recert takes 1m30s instead of the expected
30s and we'd like to know more about why that happened
> Summary run time duration breakdown

- src/ocp_postprocess.rs
Turns out both `webhook-authenticator` and
`webhook-authenticator-<latest_revision>` have to be the same. I
initially assumed the one without the suffix is simply the first
revision, so I deleted it, but it actually always equals (actually just
the data segment should be equal) to the latest revision, otherwise a
rollout is triggered. So we have to make sure both are updated.
> Modify both `webhook-authenticator` and `webhook-authenticator-<latest_revision>`

- src/ocp_postprocess.rs
Now we're also modifying the webhook-authentication-integrated-oauth
secret, which is in a different namespace and also has this kubeConfig
field, and also seems to trigger a rollout if left out of sync.
> Also sync `webhook-authentication-integrated-oauth`

- src/ocp_postprocess/cluster_domain_rename/etcd_rename.rs
Avoid parsing YAML for now until
https://github.com/openshift/cluster-kube-scheduler-operator/pull/523 is
fixed, use dumb regex instead
> Modify scheduler & KCM kubeconfig YAML no parsing

- src/cluster_crypto/crypto_utils.rs
- src/recert.rs
- src/rsa_key_pool.rs
* Ensure openssl version is major 3 (major 1 behaves differently, e.g.
PKCS#1 RSA private keys by default instead of PKCS#8)
* A few missing contexts
> Improve error handling

- src/ocp_postprocess/hostname_rename/etcd_rename.rs
> Fix etcd rollout

- src/config.rs
We don't want to silently ignore them, it defeats user expectations
> Unknown config keys should be an error

- src/ocp_postprocess/ip_rename/etcd_rename.rs
In OCP 4.15, recert with the IP replacement enabled fails due to a `networkoperator` annotation missing. This change makes this IP replacement a soft one, but added a `TODO` as we should still verify whether it should actually be a soft one or not.
> MGMT-16857: Fix error of missing networkoperator annotation

- src/ocp_postprocess/cluster_domain_rename/rename_utils.rs
This change skips a `kube-apiserver` rollout in OCP 4.15, which is triggered because of one of the kube-apiserver config arguments.  
Specifically,  the `service-account-jwks-uri` config arg contains a URI with the `api` label, instead of the `api-int` one and the cluster domain. To ensure compatibility with previous (and potentially new) OCP versions, we now match both the `api` and `api-int` labels when replacing the cluster domain in that field.
> MGMT-16875: Skip kube-apiserver rollout in OCP 4.15

- run_seed.sh
- src/config.rs
- src/config/cli.rs
- src/ocp_postprocess.rs
- src/ocp_postprocess/pull_secret_rename.rs
- src/ocp_postprocess/pull_secret_rename/etcd_rename.rs
- src/ocp_postprocess/pull_secret_rename/filesystem_rename.rs
- src/ocp_postprocess/pull_secret_rename/utils.rs
- src/recert.rs
Change pull secret in all machine configs
Change pull secret in mcd currentconfig and mcs files
> MGMT-16873: Change pull secret as part of recert reconfiguration

- src/ocp_postprocess/ip_rename/etcd_rename.rs
When trying to find the --etcd-servers arg of the oauth-apiserver deployment container command, in order to replace the seed IP with the recipient IP, recert did not include single quotes in the find string. The oauth-server regexp-s for shell escapes and encodes the arg value that matches. That made IPv6 IPs, which contain '[' (and ']'), be missed by recert previously.
- https://github.com/openshift/cluster-authentication-operator/blob/master/pkg/controllers/common/arguments/arguments.go#L13
> MGMT-17018: Fix oauth-apiserver deployment IP replacement

- src/cluster_crypto/scanning.rs
1b831fa229315feb5900300d648423dce3864145 introduced a bug, this fixes
it. It was simply reading from the wrong JSON pointer.
This is only a problem in clusters that have custom certificates set in
their OpenShift Image config
```
Error: scanning and recertification
Caused by:
0: discovering external certs to ignore
1: must be string
```
> Fix `get_openshift_image_trusted_certs` bug

- src/config.rs
The pull secret should not be included in the clean summary.
Also to cleanly test this I had to refactor the config parsing code a
bit
> Redact pull secret from clean summary

- src/ocp_postprocess/proxy_rename/etcd_rename.rs
We had a too strict condition, see diff comment
Prevents the follow error:
```
Caused by:
0: performing ocp specific post-processing
1: renaming proxy
2: renaming all
3: renaming etcd resources
4: fixing storages
5: no "/kubernetes.io/operator.openshift.io/storages/cluster"
: exit status 1
```
> Support proxy change in clusters without storage

- src/ocp_postprocess/hostname_rename/etcd_rename.rs
This PR makes the `etcd-all-certs` secret data key replacement in the OCP post-process hostname rename flow optional, as there are cases where the `managedFields` are missing. In the latter case, recert would fail with the respective error.
> OCPBUGS-32514: Fix recert failing because of non-existent managedFields

- src/ocp_postprocess.rs
Add OCP post-process CVO status update change to release-4.17.
> Add OCP post-process CVO status update to release-4.17

- run_seed.sh
- src/config.rs
- src/config/cli.rs
- src/k8s_etcd.rs
- src/recert.rs
in order to remove defragmentation code from lca , adding it to recert with flag, so that we would run it only on demand
> Add etcd defragmentaion option

- .tekton/build-pipeline.yaml
- .tekton/recert-4-19-pull-request.yaml
- .tekton/recert-4-19-push.yaml
- renovate.json
Backport Konflux fixes from main to release-4.19
- [CNF-15329](https://issues.redhat.com//browse/CNF-15329): Fix conforma failures
- [CNF-15329](https://issues.redhat.com//browse/CNF-15329): Fix renovate.json configuration
> CNF-15329: Backport Konfluxes fixes from main to release-4.19

- .tekton/recert-4-19-pull-request.yaml
- .tekton/recert-4-19-push.yaml
Update the branch Konflux is checking against
> [release-4.19] Update Konflux target branch to release-4.19

- .tekton/build-pipeline.yaml
- Update Konflux tasks to newest versions
- Add new image_digest parameter where required
> [release-4.19] Update konflux references

- .tekton/recert-4-19-pull-request.yaml
- .tekton/recert-4-19-push.yaml
Update `on-cel-expression` values for tekton pipelines to limit unnecessary builds
> [release-4.19] Update `on-cel-expression` values

- .tekton/build-pipeline.yaml
- .tekton/recert-4-19-pull-request.yaml
- .tekton/recert-4-19-push.yaml
- Add skip for sast-coverity task
- Migrate to new service account configuration
> [release-4.19] Konflux build configuration updates

- .tekton/build-pipeline.yaml
Reverts rh-ecosystem-edge/recert#318
> Revert "Update Konflux references"

- .tekton/build-pipeline.yaml
Reverts rh-ecosystem-edge/recert#321
> Revert "chore(deps): update konflux references"

- .konflux/lock-build/rpms.in.yaml
- .konflux/lock-runtime/rpms.in.yaml
- .konflux/lock-runtime/rpms.lock.yaml
Backport of https://github.com/rh-ecosystem-edge/recert/pull/580
> [release-4.18] CNF-19739: Add missing EUS repos to rpm lock configuration

- .konflux/lock-build/rpms.in.yaml
- .konflux/lock-runtime/rpms.in.yaml
- .konflux/lock-runtime/rpms.lock.yaml
Backport of https://github.com/rh-ecosystem-edge/recert/pull/580
> [release-4.17] CNF-19739: Add missing EUS repos to rpm lock configuration

- .konflux/lock-build/rpms.in.yaml
- .konflux/lock-runtime/rpms.in.yaml
- .konflux/lock-runtime/rpms.lock.yaml
Backport of https://github.com/rh-ecosystem-edge/recert/pull/580
> [release-4.16] CNF-19739: Add missing EUS repos to rpm lock configuration
